### ISSUE TITLE
Using it for live transcriptions?

### ISSUE THREAD

**Issue by andupotorac** [Dicklesworthstone/llm_aided_transcription_improvement#2]
Hi there. We're using [Gladia](https://www.gladia.io/) which is based on Whispr. I'm wondering if this could be used for real-time transcriptions, maybe using Groq with Llama 3.1.

**Comment by Dicklesworthstone** [comment]
I don't think that would work as well because it wouldn't have as much context. I guess you could do it with a lag of a minute or two.

**Comment by andupotorac** [comment]
> I don't think that would work as well because it wouldn't have as much context. I guess you could do it with a lag of a minute or two.

Needs to be in real time. Alright, so no go. :)
